### PR TITLE
Added safety check in utils

### PR DESCRIPTION
**Pull request by PankajTrifacta**
Added safety check in utils

### CODE REVIEW

**Review by hodos — COMMENTED** [review]
Should we also check for `viewWrapper.current` existence everywhere we access it?

**Comment by PankajTrifacta** [comment]
> Should we also check for `viewWrapper.current` existence everywhere we access it?

I also thought about that, but cross verified on react-digraph site they seems to be doing the same. So was not sure if its a overkill or needed, what do you think

https://github.com/uber/react-digraph/blob/master/src/components/graph-view.js

**Comment by PankajTrifacta** [comment]
> Should we also check for `viewWrapper.current` existence everywhere we access it?

Ignore this change I think entities works fine, just check was need in utils

**Comment by PankajTrifacta** [comment]
> Should we also check for `viewWrapper.current` existence everywhere we access it?

Updated to add just a safety check, after each for plan-rtl was getting entities as null since it was getting called async, they are working fine now.


Ideally willunmount should take care of clearing animation frame and timeouts, checking locally if that works

**Review by hodos — APPROVED** [review]

**Pull request merged**
